server:
  port: ${PORT:8080}
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${GROUP_CONSUMER:grupo-sky}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      name: ${TOPIC:teste}
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:db
      username: sa
      password: password
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show_sql: false
      format_sql: true
      ddl-auto: update
  datasource:
    initialization-mode: always
